### ISSUE TITLE
itimerspec or timer_fd not available on macOS for Timer

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#1]
Hi,

I tried to compile the latest commits of SeisComP4 on macOS 10.14.6.

It worked pretty well until it failed to compile setInterval() for the new messaging service in `master/apps/messaging/scmaster/timer.cpp`.
https://github.com/SeisComP/common/blob/master/apps/messaging/scmaster/timer.cpp

On macOS there is no itimerspec structure (or the POSIX timer functions (timer_*()) 
(and no `timerfd_create()` and `timerfd_settime()`) since it's Linux / glibc specific (I thinj),
and neither Homebrew or macports can install glibc 2.31.

Maybe I could rewrite setInterval with clock_gettime, since macOS 10.12 now supports clock_gettime() 
https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

Do you think that clock_gettime() could be used to create a setInterval() function ?

Any suggestions is greatly appreciated.

Here's the compilation output:
```/Users/gilles/Development/seiscomp4-git/seiscomp4-macos/src/base/common/apps/messaging/scmaster/timer.cpp:60:20: error: variable has incomplete type 'struct itimerspec'
        struct itimerspec newValue;
                          ^
/Users/gilles/Development/seiscomp4-git/seiscomp4-macos/src/base/common/apps/messaging/scmaster/timer.cpp:60:9: note: forward declaration of 'itimerspec'
        struct itimerspec newValue;
               ^
/Users/gilles/Development/seiscomp4-git/seiscomp4-macos/src/base/common/apps/messaging/scmaster/timer.cpp:64:41: error: use of undeclared identifier 'TFD_NONBLOCK'
                _fd = timerfd_create(CLOCK_MONOTONIC, TFD_NONBLOCK);
```

**Comment by gempa-jabe** [comment]
Hi Gilles,

thank you for looking into it. Actually the timer is an implementation of an asynchronous timer device which can be used in combination with select, epoll or kqueue. I do not need a method to measure time and to actively wait until a certain duration has elapsed but to get informed by the kernel asynchronously. I am not sure how to implement that in OSX or BSD but I will look into it when time permits.

I am pretty sure that there are alternatives. I did that already for the wired library (part of SeisComP that handles asynchronous devices) and added support for kqueue on BSD/OSX although that haven't been tested extensively.

Regards,
Jan

**Comment by gempa-jabe** [comment]
Actually inspecting your output, the compiler does not complain about the missing include for "sys/timerfd.h". So `timerfd_create` should be available. Futhermore `itimerspec` has been used in `utils/timer.cpp` since years and seems to compile under OSX.

Can you figure out where itimerspec is defined?

And maybe `TFD_NONBLOCK` is also available but we just haven't included the right file.

**Comment by gempa-jabe** [comment]
As a first shot I have removed the struct declaration. Please give it another try and report back with the compiler error.

**Comment by gilcel** [comment]
> Actually inspecting your output, the compiler does not complain about the missing include for "sys/timerfd.h". So `timerfd_create` should be available. Futhermore `itimerspec` has been used in `utils/timer.cpp` since years and seems to compile under OSX.
> 
> Can you figure out where itimerspec is defined?
> 
> And maybe `TFD_NONBLOCK` is also available but we just haven't included the right file.

Oh sorry, I forgot to mention that yesterday I did put the __APPLE__ preprocessor definition 

```
#ifndef __APPLE__
#include <sys/timerfd.h>
#endif
```
Removing it gives the error:
```
seiscomp4-macos/src/base/common/apps/messaging/scmaster/timer.cpp:36:10: fatal error: 'sys/timerfd.h' file not found
#include <sys/timerfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```
Also removing the struct declaration doesn't fix it...
```
error: unknown type name 'itimerspec'; did you mean
      'timespec'?
        itimerspec newValue;
        ^~~~~~~~~~
        timespec
```

Was `itemerpsec`and `timerfd_create` used in seiscomp3 before ? I need to check

**Comment by gempa-jabe** [comment]
See https://github.com/SeisComP3/seiscomp3/blob/master/src/trunk/libs/seiscomp3/utils/timer.cpp#L238.

**Comment by gempa-jabe** [comment]
OK, for kqueue we have to use EVFILT_TIMER. At least for BSD and I hope that OSX follows the implementation. That does not fit nicely into the usage of the library currently and will need some work I think.

**Comment by gilcel** [comment]
> See https://github.com/SeisComP3/seiscomp3/blob/master/src/trunk/libs/seiscomp3/utils/timer.cpp#L238.

Ok thanks...how did I miss this ? ;-)

**Comment by gilcel** [comment]
Here's how I rewrote timer.cpp for seiscomp3:
https://github.com/gilcel/seiscomp3-macos/blob/master/src/trunk/libs/seiscomp3/utils/timer.cpp

**Comment by gempa-jabe** [comment]
Ah, OK.

I committed a quick test in 84bb6013efe7e1546baa1df4feebbd7b15fc0d5f. You can give it a try if it compiles. I don't like this fix and probably won't ever merge it into master.

**Comment by gilcel** [comment]
I'm still compiling your 86bb601 version...have some issues with OpenSSL library not found in
..base/common/libs/seiscomp/wired/devices/socket.h:27:10: fatal error: 'openssl/ssl.h' file not found
Although cmake finds OpenSSL include dir etc.
it drives me mad ;-(

**Comment by gilcel** [comment]
OK I managed to compile SeisComP4 for macOS with your https://github.com/SeisComP/common/commit/84bb6013efe7e1546baa1df4feebbd7b15fc0d5f commit and with Qt5 the integration is much better than with Qt4.

Well I have not setup MySQL yet but `scconfig``scolv`, `smcv` all run well but when trying to launch `scmaster` I get an assertion failed error.
Removing the line in question and recompiling and restarting `scmaster`nothing happens (no GUI ?)...is this normal ?
```
./scmaster 
Assertion failed: (_isActive == true), function deactivate, file /Users/gilles/Development/seiscomp4-git/seiscomp4-macos/src/base/common/libs/seiscomp/utils/timer.cpp, line 302.
Abort trap: 6
```

![seiscomp4-scolv-screenshot](https://user-images.githubusercontent.com/9282533/79639501-85e4f280-818c-11ea-8a46-9bfd7a85aee1.png)

**Comment by gempa-jabe** [comment]
>  Removing the line in question and recompiling and restarting scmasternothing happens (no GUI ?)...is this normal ?

scmaster is the messaging daemon, it does not bring up a GUI. You can visit it's webpage as it also serves as an http server: http://localhost:18180

How did you manage to get around the openssl include issue?

**Comment by gilcel** [comment]
For the Homebrew OpenSSL include I had to do set CPATH manually.
I will try to find a more elegant solution since it worked for seiscomp3...
```
export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
export CPATH=$(brew --prefix openssl)/include
```

Hmm I couldn't open the http server at port 18180...I will look at it further.
Also trying to find an alternative for timer_t on macOS since it's missing.
Maybe a solution here:
https://stackoverflow.com/questions/44807302/create-c-timer-in-macos

**Comment by gilcel** [comment]
> OK, for kqueue we have to use EVFILT_TIMER. At least for BSD and I hope that OSX follows the implementation. That does not fit nicely into the usage of the library currently and will need some work I think.

So yes kqueue is available on macOS according to Wikipedia:
https://en.wikipedia.org/wiki/Kqueue

Also EVFILT_TIMER should work on macOS:
https://nitschinger.at/Scheduling-Timers-on-OS-X-with-Rust-and-Kqueue/

**Comment by gempa-jabe** [comment]
Great. That would be the correct fix I think but as I said, it requires more work and core changes.

**Comment by gempa-jabe** [comment]
> For the Homebrew OpenSSL include I had to do set CPATH manually.
> I will try to find a more elegant solution since it worked for seiscomp3...

I have commited a change which set the OpenSSL include directory on top-level. Maybe that solves already your issue.

**Comment by gilcel** [comment]
> I have commited a change which set the OpenSSL include directory on top-level. Maybe that solves already your issue.

Thanks! I made the changes but unfortunately it doesn't work, always the same error:
`common/libs/seiscomp/io/socket.h:29:10: fatal error: 'openssl/ssl.h' file not found`

Even changing adding the following code at line 54 to `cmake/FindOpenSLL.cmake` doesn't work:

```
IF (APPLE)
    # Check if OpenSSL was installed by Homebrew in /usr/local/opt/openssl/
	MESSAGE("Checking Homebrew version of OpenSSL in /usr/local/opt/openssl/")
	IF (EXISTS "/usr/local/opt/openssl/lib/libssl.dylib" AND EXISTS "/usr/local/opt/openssl/lib/libcrypto.dylib" )
	    SET(OPENSSL_INCLUDE_DIR "/usr/local/opt/openssl/include/")
		SET(OPENSSL_SSL_LIBRARY "/usr/local/opt/openssl/lib/libssl.dylib")
  		SET(OPENSSL_CRYPTO_LIBRARY "/usr/local/opt/openssl/lib/libcrypto.dylib")
  		SET(CRYPTO "/usr/local/opt/openssl/lib/libcrypto.dylib")
  		SET(crypto "/usr/local/opt/openssl/lib/libcrypto.dylib")
  		SET(SSL ${OPENSSL_SSL_LIBRARY})
  		SET(OPENSSL_LIBRARIES ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
  		MESSAGE(STATUS "Homewbrew OpenSSL version found: ${OPENSSL_VERSION} ${OPENSSL_INCLUDE_DIR} ${OPENSSL_LIBRARIES}")
	ELSE()
	    MESSAGE(FATAL_ERROR "Could NOT find Homebrew version of OpenSSL in /usr/local/opt/openssl/")
	ENDIF()
ENDIF (APPLE)
```

The only solution so far is to set CPATH manually to:
`export CPATH=/usr/local/opt/openssl/include`
or:
`export CPATH=$(brew --prefix openssl)/include`

Here's a good explanation:
http://trivialanalog.de/blog/how-to-compile-git-under-mac-os-x-el-capitan.html

**Comment by gempa-jabe** [comment]
> Thanks! I made the changes but unfortunately it doesn't work, always the same error:

For which file? Which cpp file does it try to compile? Actually the `INCLUDE_DIRECTORY` is exactly meant for this. You can try to run make in verbose mode and check the command line if your include directory is correctly set:

```
$ VERBOSE=1 make
```

**Comment by gilcel** [comment]
> For which file? Which cpp file does it try to compile?

I applied your commit:  https://github.com/SeisComP/common/commit/a96e4c76b36d2820d095a3f19a6dac2aa3a1fe9(for OpenSSL change(s)) 
but stops at:
```
[ 70%] Building CXX object src/base/main/apps/tools/inventory/fdsnxml2inv/CMakeFiles/fdsnxml2inv.dir/fdsnxml/phone.cpp.o
In file included from ...seiscomp4-macos/src/base/main/apps/tools/ql2sc/app.cpp:17:
In file included from ...seiscomp4-macos/src/base/main/apps/tools/ql2sc/app.h:19:
In file included from ...seiscomp4-macos/src/base/main/apps/tools/ql2sc/quakelink.h:22:
In file included from ...seiscomp4-macos/src/base/main/../common/libs/seiscomp/io/quakelink/connection.h:26:
...seiscomp4-macos/src/base/main/../common/libs/seiscomp/io/socket.h:29:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
3 warnings generated.
```

Setting `export CPATH=/usr/local/opt/openssl/include`then it compiles fine...

Is not a ```target_link_libraries(
    OpenSSL::SSL
 )```
missing ?

**Comment by gempa-jabe** [comment]
> Is not a target_link_libraries( OpenSSL::SSL ) missing ?

No, we are still compiling and not linking. I have just moved my openssl headers to `/opt/test` and configured the path with cmake. Everything compiles and finds the headers.

Your output suggests that `src/base/common` compiled fine. Can you confirm that by changing into the build directory `src/base/common` and run make?

**Comment by gilcel** [comment]
OK thanks but I'll try tomorrow: something's wrong with my test-machine at my office (remotely), can't access it from my home anymore :-(
