### ISSUE TITLE
Proposal: updating the TravelTimeTableInterface

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#109]
Dear developers,

I would like to suggest a couple of changes to the `TravelTimeTableInterface` and hear your opinions on that. 

1 - add a `TravelTimeTableInterface::computeTravelTime` method that returns only the travel time without additional information (no `TravelTime` is returned). This is because the travel time is the most requested information from the `TravelTimeTableInterface` throughout seiscomp and this change would allow to improve the overall performance, since returning only the travel time can potentially be less expensive than returning all the fields of the `TravelTime` class.

2 - add a field `azimuth` to the `TravelTime` class. This is to allow 3D velocity models in the future. In a 3D velocity model the azimuth of the take off angle is calculated by the travel time table, because the ray horizontal path can be reflected/refracted/bent the same way it happens with the vertical ray path on a 1D model.  This change would make the existing 1D models return the azimuth computed by e.g. delazi. 

What are your thoughts on this?

thanks,
Luca

**Comment by gempa-jabe** [comment]
I am fine with both suggestions. The azimuth can also be set to undefined in current models.

**Comment by luca-s** [comment]
You mean like setting the azimuth to nan? That seems interesting, I didn't think about it. It might have some advantages, like properly communicating that value is not handled by the ttt. On the other hand, returning a value, e.g. from delazi, centralize at api level the precision of the azimuth computation. I believe both solutions have good points. 

Either way, if you agree, I will provide a PR for this.

**Comment by gempa-jabe** [comment]
`nan` would be an option, indeed. I had `OPT(double)` in mind. If the `delazi` computation does not add too much computational overhead to the default implementation, I am also fine with it.

**Comment by gempa-jabe** [comment]
Please create your PR and we can continue to discuss the code.
