### ISSUE TITLE
Fails to compile common/libs/seiscomp/utils/timer.cpp

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#116]
clang & gcc fails to compile SeisComP v6:
Error at line 352 & 366 of `common/libs/seiscomp/utils/timer.cpp`

Line 352 & line 366 still contains `boost::mutex`
`boost::mutex::scoped_lock lk(_mutex);`

This works for me when replacing with:
`std::lock_guard<std::mutex> lk(_mutex);`

**Comment by gempa-jabe** [comment]
Fortunately this only affects non Linux builds. You are right, it must be `std::mutex`.

**Comment by gempa-jabe** [comment]
I have changed it, please try again.

**Comment by gilcel** [comment]
Thanks! I pushed your commits: d85672e & 7ba8429 to my macOS port and it compiles fine now on Mac Apple Silicon & Mac INTEL (macOS Sonoma).
