### ISSUE TITLE
class WebsocketProxy InterruptibleObject implicitly declared private

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#117]
Compiling with clang (and g++-13.2) (with C++11 or C++14)  the following error is displayed in `common/libs/seiscomp/messaging/database/websocket_private.h` for class:

`class WebsocketProxy : public Seiscomp::IO::DatabaseInterface,
                       virtual Seiscomp::Core::InterruptibleObject {`

clang error:

```
class WebsocketProxy InterruptibleObject implicitly declared private in 
/src/base/common/libs/seiscomp/messaging/database/websocket_private.h:37:24: note: implicitly declared private here
                       virtual Seiscomp::Core::InterruptibleObject {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I fixed it by appending `public` to `virtual` like this:

```
class WebsocketProxy : public Seiscomp::IO::DatabaseInterface,
                       virtual public Seiscomp::Core::InterruptibleObject {
```

But I'm not 100% sure if this is correct....

**Comment by gempa-jabe** [comment]
Yep, that is correct. I am going to push the fix.
