### ISSUE TITLE
LocatorInterface question

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#141]
Dear developers,

I would like to ask about the different location [methods](https://github.com/SeisComP/common/blob/4c37b230bb60a1baa6f56ac204a9b2eeed06de4d/libs/seiscomp/seismology/locatorinterface.h#L164C1-L168C76):

```
virtual DataModel::Origin *locate(PickList& pickList) = 0;
virtual DataModel::Origin *locate(PickList& pickList,
                                 double initLat, double initLon, double initDepth,
                                const Core::Time &initTime) = 0;
virtual DataModel::Origin *relocate(const DataModel::Origin *origin) = 0;
```

What is the purpose of each method? Also,  looking in the SeisComP code I could only see `relocate` used.

thanks
Luca

**Comment by gempa-jabe** [comment]
There are other modules which are using the `locate` functions. The purpose was to let a particular locator find the best solution based on a list of picks, basically without having an origin. `lambda` makes use of it. Probably those functions haven't been found to be very useful in general over the years but they are still there ;)

**Comment by luca-s** [comment]
Thanks @gempa-jabe. I had my own idea on what should be called in a specific situation and I just wanted to double-check with you.
