### ISSUE TITLE
c++17 compilation errors for std::binary_function and std::pointer_to_binary_function

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#148]
Compiling with c++17 gives the following error:
`base/common/libs/seiscomp/math/filter.cpp:87:23: error: no template named 'binary_function'; did you mean '__binary_function' ?`

These errors occurs since `std::binary_function` `std::pointer_to_binary_function` were removed in C++17
https://en.cppreference.com/w/cpp/utility/functional/binary_function

https://en.cppreference.com/w/cpp/utility/functional/pointer_to_binary_function

`std::pointer_to_binary_function` is used in:
- `base/main/apps/tools/scimex/imeximpl.cpp` and
- `base/main/apps/tools/scm/plugins/mncursesplugin.cpp`

**Comment by gempa-jabe** [comment]
I am on the way on fixing it ...

**Comment by gempa-jabe** [comment]
Please give it another try

**Comment by gilcel** [comment]
It compiles fine now for the replacements of `binary_function`and `pointer_to_binary_function` 👍 Thanks!

But error for `std::bind2nd` and `std::ptr_fun`, which were also removed in C++17 and are used in: 
`main/apps/tools/scm/seiscomp/plugins/monitor/monitorplugininterface.cpp`

**Comment by gempa-jabe** [comment]
Question is why gcc does not enforce that. It compiles fine there.

**Comment by gilcel** [comment]
Well forgot to mention that I'm using clang 16 maybe...but by searching on the net it seems that gcc 14.x has the same issue with it

**Comment by gempa-jabe** [comment]
Fixed

**Comment by gilcel** [comment]
There are still some fun pointers it seems ( `ptr_fun` ) in 

`main/apps/gui-qt/scmv/stationdata.cpp:39: 	iterator it = std::find_if(_data.begin(), _data.end(), std::bind1st(std::ptr_fun(compareIDs), id));`

`main/apps/gui-qt/scmv/stationdatahandler.cpp:88: 	                                         std::ptr_fun(RecordHandlerCompare));`

`main/apps/tools/scm/plugins/memailplugin.cpp:503: 					bind2nd(ptr_fun(findName), rcIt->first)`

**Comment by gempa-jabe** [comment]
I will have a more careful look later. I just thought about the few occurrences you showed but it seems to turn out as an endless story. It also needs testing ...

**Comment by gilcel** [comment]
FYI: everything compiles fine now with clang and C++17...but not tested yet.
