### ISSUE TITLE
Quick fix for auto keyword in certstore.cpp findCertificate()

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#149]
I'm getting the following error when compiling `base/common/libs/seiscomp/utils/certstore.cpp` with clang v16.0.0 on macOS:

`src/base/common/libs/seiscomp/utils/certstore.cpp:106:20: error: no matching function for call to 'X509_cmp_time'`

Fixed it by replacing the `auto` keyword with its explicit type `time_t`:

```
const X509 *CertificateContext::findCertificate(const Core::Time &referenceTime) const {
	SEISCOMP_DEBUG("Certificate lookup");

auto seconds = referenceTime.epochSeconds();
```

to:

```
const X509 *CertificateContext::findCertificate(const Core::Time &referenceTime) const {
	SEISCOMP_DEBUG("Certificate lookup");

time_t seconds = referenceTime.epochSeconds();
```

This is of course a fix for clang, so gcc does maybe a better job for this ?

**Comment by gempa-jabe** [comment]
Please check the latest master again.

**Comment by gilcel** [comment]
Fixed with https://github.com/SeisComP/common/commit/f92048d291f86e09577ef62bed9a5b8c08cd2c46
Can be closed! Thanks!
