### ISSUE TITLE
Infinite loop while reading miniseed files

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#19]
Dear developer,

it seems that the recent changes to mseedrecord.cpp caused an infinite loop while reading certain miniseed files. I found the bug while reading from an SDS archive. From the logs I can see the following:

```
[error/SDS] exc: -1, Fatal error occured during reading record from stream
[error/SDS] exc: -1, Retrieving the record length failed
[error/SDS] exc: -1, Retrieving the record length failed
[error/SDS] exc: -1, Retrieving the record length failed
[error/SDS] exc: -1, Retrieving the record length failed
[error/SDS] exc: -1, Retrieving the record length failed
[...same error forever...]
```

From the debugger I can see the issue is caused by a combination of [MSeedRecord::read()](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/records/mseedrecord.cpp#L713) and the [SDSArchive::next()](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/recordstream/sdsarchive.cpp#L743): 
- `MSeedRecord::read()` [throws](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/records/mseedrecord.cpp#L844) `LibmseedException("Retrieving the record length failed")`
- then `SDSArchive::next()` [catches it](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/recordstream/sdsarchive.cpp#L837) and tries to [read](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/recordstream/sdsarchive.cpp#L822) the stream again
- ... but it will [throws](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/records/mseedrecord.cpp#L844) again with the same error as before...
- ...the exception will be [catched](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/recordstream/sdsarchive.cpp#L837) again 
- ... and the stream tried to be [read](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/recordstream/sdsarchive.cpp#L822) again
- ....and that continues forever

`MSeedRecord::read()` fails repeatedly because the input stream, which is passed in input, is in an invalid state and never updated. [The stream status is checked at the begin of the method](https://github.com/SeisComP/common/blob/f862728b9eb45c9f763ee9d1ef4a060da75e5d04/libs/seiscomp/io/records/mseedrecord.cpp#L721). The check fails every  time, the method throws, but the stream is left unchanged. That leads to the infinite loop.

Hope this helps

**Comment by gempa-jabe** [comment]
Luca, can you share an example file that exhibits this issue? The question is what is the actual stream status if not "eof"?

**Comment by luca-s** [comment]
@gempa-jabe I will try to give you the file and more information. Also let me add  that the code didn't get stuck forever in the previous versions of SeisComP, so the issue is in the new logic.

**Comment by luca-s** [comment]
Thank you. I will try it and report back here.

> And this might be an opportunity to check your archive, there seems to be something wrong with your files. ;)

That's for sure :) However I didn't expect the code to read wrong data, I just thought it was useful to report that the code can get stuck forever

**Comment by gempa-jabe** [comment]
Of course it was useful to report the issue. The code must be able to deal with binary garbage.

**Comment by luca-s** [comment]
The fix you provided seems to have solved the problem, thank you @gempa-jabe !
