### ISSUE TITLE
Forced plugin loading

### ISSUE THREAD

**Issue by damb** [SeisComP/common#25]
Hi devs,

is there a clean way for concrete implementations of `Seiscomp::System::Application` to guarantee that certain plugins are always loaded when being run? If I understand the `Seiscomp::System::PluginRegistry` API correctly facilities for forced plugin loading are currently not provided.

Though, there is a *hacky* workaround i.e. to modify both `_configuration` and `_baseSettings` members in an overloaded version of `Seiscomp::System::Application::initPlugins()`. Can you think of a cleaner approach of implementing this feature?

Thanks.

Daniel

**Comment by gempa-jabe** [comment]
Actually that would not make much sense as filenames of plugins are just containers without any implications about their implementations. If you require a certain interface to be implemented then you should check in your init method if all required interfaces are available, e.g.:

```c++
if ( !DatabaseInterfaceFactory::Find("sqlite3") ) {
  cerr << "ERROR" << endl;
  return false;
}
```

Even though you are not guaranteed that a particular interface name is really implemented the way you expect it, it is a better approach. If you really require a certain code in your application then link against it.

**Comment by damb** [comment]
> If you really require a certain code in your application then link against it.

You are correct. This is the way to go. Thanks for your input.
