### ISSUE TITLE
Small bug in common/libs/seiscomp/gui/map/projections/mercator.cpp

### ISSUE THREAD

**Issue by gilcel** [SeisComP/common#3]
In `common/libs/seiscomp/gui/map/projections/mercator.cpp` at line 23, it should be:

`#include <seiscomp/gui/map/texturecache.ipp>`
instead of
`#include <seiscomp3/gui/map/texturecache.ipp>`

then it compiles fine (at least on macOS)

**Comment by gempa-jabe** [comment]
Thanks, I fixed it.
