### ISSUE TITLE
Misleading comment on `Client::Application::init()`

### ISSUE THREAD

**Issue by damb** [SeisComP/common#35]
Hi devs,
on one hand the documentation of the *initialization configuration methods* i.e. https://github.com/SeisComP/common/blob/4a21f09c17f4aadc4091c845c0b1d52c77d30098/libs/seiscomp/client/application.h#L250-L253 says that methods should be called **before** calling the `init()` method, while on the other hand within the same *section* the methods https://github.com/SeisComP/common/blob/4a21f09c17f4aadc4091c845c0b1d52c77d30098/libs/seiscomp/client/application.h#L388-L407 are documented in a way that they should be called **after** the `Application::init()` method.

- Which `Application::init()` method the documentation is referring to? 

Perhaps this is a little bit petty. Anyway, I think the documentation could be clearer. What's your opinion on that?

**Comment by gempa-jabe** [comment]
I agree. In https://github.com/SeisComP/common/blob/4a21f09c17f4aadc4091c845c0b1d52c77d30098/libs/seiscomp/client/application.h#L388 ends the section of setup methods which must be called **before** `init()`. A new section will be added to reflect that.

**Comment by damb** [comment]
Great thanks.
