### ISSUE TITLE
Why is SAC format not supported in File RecordStream?

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#39]
This is just a question. I had a look at the code in [here](https://github.com/SeisComP/common/blob/2f3d8729ebbd666e821d6e9950b86f00534fdee5/libs/seiscomp/io/recordstream/file.cpp#L117) and I noticed that SAC is not supported, although the actual SacRecord implementation exists. This is just a curiosity, but also I would like to understand if there are limitations to be aware of, since I need to implement my own Record format. 

Thanks.

**Comment by gempa-jabe** [comment]
That is true. It hasn't been added to the file extensions. Nevertheless you can open a file and set the record type later with e.g. `rs->setRecordType("sac")`. If you want to support that without changing code then accept a URI and pass `sac` as anker: `RecordStream::Open("file:///path/to/file.data#sac`"). For any given type a factory must exist which returns the actual implementation (`REGISTER_RECORD(SACRecord, "sac");`).

**Comment by luca-s** [comment]
Thanks for the clarification.
