### ISSUE TITLE
Question on RecordStream::addStream implementations across RecordStreams

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#44]
I noticed an inconsistency of the [RecordStream::addStream](https://github.com/SeisComP/common/blob/master/libs/seiscomp/io/recordstream.h#L121) method across different implementations.  

It seems to me that `SDSArchive` and `File` recordstreams allow only one time window (startTime, endTime) per stream (net.sta.loc.cha) to be requested. More precisely, whenever a second call to `addStream` happens on the same stream (net.sta.loc.cha), that call erases the previous time window (startTime, endTime) requested. 

Looking at the code the behaviour seems to be wanted like that and not a bug. Can you confirm that?

However I feel that is a big inconsistency compared to other `RecordStream` implementations, because it invalidates the portability of the code across different `RecordStream`s.

thanks.

**Comment by luca-s** [comment]
any feedback?

**Comment by gempa-jabe** [comment]
That behaviour is intended. There is actually no backend available which supports multiple time windows per stream. Where do you see inconsistencies actually?

**Comment by luca-s** [comment]
If the behaviour is intended,  then there are not issues. 

> There is actually no backend available which supports multiple time windows per stream. 

I believe that at least  `Seedlink`, `fdsnws`, `arclink` and probably others support  multiple time windows per stream.  That's why I thought it was a feature of `RecordStream`, until I stumbled across the issue of the implementation of `SDSArchive` and `File`.  That is the inconsistency, which could result in a different behaviour between real-time and playback.

However, if that is the intended design, it means all seiscomp modules where written with that limitation in mind, so I simply note it and keep in mind for the future ;)

However, it's a pity to have that limitation. `SDSArchive` and `File` would work much faster if a module could specify all the streams in one batch instead of the current behaviour where the a file is read multiple time to access  several time windows.

**Comment by gempa-jabe** [comment]
> But it's a pity to have that limitation. SDSArchive and File would work much faster if a module could specify all the time windows in one batch instead of the current behaviour where the a file is read multiple time to access several time windows.

The recordstream interface and implementations were created with processing in mind. And all our processing works with single time windows per stream. Also the GUIs do not support requests with multiple time windows per stream and we never have had the wish to support it. Up until now I haven't treated that as a limitation ;)

I am not sure if `Seedlink` supports that. @andres-h may confirm that.

**Comment by luca-s** [comment]
One last comment. Suppose we have a module that reads the waveforms of an origin phases, both P and S. The code doesn't subscribe to real-time streams, but it reads waveforms on demand, similarly to `scamp`. For the S phases all 3 components are requested,  because the code needs to project those to ZRT. For the P phases only the Z component is requested.

The obvious implementation is to read the waveforms in batch, all at once, otherwise there would be performance issues in opening/closing multiple RecordStreams (in realtime that would mean Seedlink connections).  Such batch request would work only in real-time, and it should be modified if that has to work also in playback with an sds archive or a simple file.

I believe the current design leaves a big burden on the modules implementations, which need to be aware of the limitation of the RecordStream. The API could handle the complexity internally instead and relieves the modules from that.

**Comment by gempa-jabe** [comment]
I mean just combining the Z component time window should be feasible and easy to implement for the application. And I am still in doubt that Seedlink can support you with such requests anyway. Otherwise it leaves a big burden to all the backends which must also support multiple time windows per channel. For real-time servers it is not as trivial as it might seem or at least not cheap. I actually don't see the big challenge for user code. We might have different opinions on this topic which is fine. If you have a concrete idea how to handle that API wise to take the "big burden" off the applications, feel free to further discuss it.

**Comment by luca-s** [comment]
> And I am still in doubt that Seedlink can support you with such requests anyway.

If this is the case, then the issue is closed. It would explain why some implementations don't bother to provide multiple time windows. I need to test it again then, because I had the impression that Seedlink could request multiple time windows.

If seedlink supports multiple time windows, then we can discuss the issue further. Thanks.

**Comment by andres-h** [comment]
Seedlink only supports one time window per station 😳

I don't remember how the recordstream is exactly implemented, but basically there are two options to emulate correct behaviour:

1. Find minimum and maximum time of all streams, make single Seedlink request and discard data that is not within time window.
2. Make individual Seedlink request per time window.

Typical (processing) use case is that all streams have the same time window anyway, eg., BH* from t1 to t2.

A problem with multiple time windows per stream is how to handle overlapping time windows? Should the overlapping data be duplicated? If yes, the client just gets duplicate data, because recordstream API does not associate received data with requested time window -- the client just receives a single data stream.

**Comment by luca-s** [comment]
Thanks @andres-h , that closes the issue. So no multiple time windows per stream allowed.

**Comment by luca-s** [comment]
I don't want to reopen the issue, but simply leaving my final comment on this matter. 

While solutions at the module level can be implemented, at each module repeatedly, I believe that a single solution at the API level would be better. Moreover, there are problems that can be solved only at API level (please consider the performance issue for the FIle and SDS RecordStream discussed earlier). That's why I raised this issue. If you consider improving the API I would be happy to help. 

Anyway, thanks a lot for your replies. You are always very helpful.

@andres-h one last question. The single window per stream limitation on the Seedlink RecordStream is a technical issue with the protocol or were you simply stating how the current implementation works?

**Comment by gempa-jabe** [comment]
> While solutions at the module level can be implemented, in each module repeatedly

I don't think that there are so many.

> Moreover, there are problems that can be solved only at API level (please consider the performance issue for the FIle and SDS RecordStream discussed earlier).

Actually not. You can combine requested for two windows into a single window and then separate the data in your app. If you want data for tw1 from channel A and also tw2 from channel A then just subscribe to channel A with tw1 + tw2 and throw away the data you don't need. I still not see the difficulty in doing so.

The app knows much better which data it requires. The API must deal with all corner cases if it is complex. The simpler the API the less bugs. As @andres-h pointed out already, resolving overlapping time windows can be ambiguous. One wants data just once, another one expects duplicate data.

>  The single window per stream limitation on the Seedlink RecordStream is a technical issue with the protocol or were you simply stating how the current implementation works?

It is how Seedlink works. It only supports **one** time window per station (channels are just subscribed via selectors).

**Comment by luca-s** [comment]
@gempa-jabe I gave you a very simple example to explain my point and let you think at the issue, but you focus on that example as if it was the only one that fails with the current API. I could give you more examples where the current API is a real bottleneck (that's why I open the issue in the first place), but I won't since it is clear you are happy with the current API. Fine, not problem. I accept that and I will leave with that ;)

**Comment by gempa-jabe** [comment]
> I gave you a very simple example to explain my point and let you think at the issue, but you focus on that example as if it was the only one that fails with the current API. I could give you more examples where the current API is a real bottleneck ...

I can't focus on anything else I don't have. That the API is a real bottleneck is a statement (which I can't leave as is) but I don't accept that statement. That is why I am arguing. The example you gave is not convincing for me and I don't have other convincing examples otherwise we would have changed the API already if there were real bottlenecks. But there aren't ...

**Comment by luca-s** [comment]
I believe SeisComP is a powerful tool for analysing historical data and I use it for processing years of data, tens of thousands of events on networks with hundreds of stations. I consider playback first class citizens as much as real-time analysis. When we talk about playback we need to consider SDS archive the default RecordStream as much as we consider Seedlink the default RecordStream in real-time.

Let's say you have a sequence of few hundreds events, that happened in a day. Each event has ~100 phases (50P and 50S), so 50 stations, which means 50 miniseed files to read per channel for every event (assuming SDS archive as RecordStream). If you need to load their waveforms with the current API, each daily miniseed file should be read few hundred times (once per event) times 2 (once per P and once per S). If the API would support multiple time windows, each file could be read only once. 

The same apply to File RecordStream. 

You can always find workarounds, and I could give you more complicated examples where the workaround doesn't work. 

The culprit is that, as you said, there are no many modules that require to load so many waveforms, so the API covers the most common case. I accept that.

**Comment by gempa-jabe** [comment]
> The culprit is that, as you said, there are no many modules that require to load so many waveforms, so the API covers the most common case. I accept that.

Yes, exactly my point. We could add a complicated implementation which tracks all the time windows and does all the complicated setup stuff and then only one application we do not even know uses it. ;)

Eventually the record stream will return record by record without context information of the requested time window. So your application must either keep track of the time windows and forward the record to the corresponding processors or you feed each record into every processor and let it do the filtering. The latter case is the most likely imho.

So when you subscribe to the data of all your events per day, then combining all time windows per channel (P and S) is a valid approach. Then feed every record into the processor and let it filter it. The file must be accessed just once. Why isn't that a valid and simple approach?

Actually if the SDS rs would supports multiple time windows it also must read record by record to throw away what you do not want. So the overhead is actually not too much.

**Comment by damb** [comment]
Sorry, that I'm entering the discussion at this quite late point.

> So when you subscribe to the data of all your events per day, then combining all time windows per channel (P and S) is a valid approach. Then feed every record into the processor and let it filter it. The file must be accessed just once. Why isn't that a valid and simple approach?

@luca-s, this could be achieved with e.g. a custom concrete implementation of [`Processing::WaveformProcessor`](https://github.com/SeisComP/common/blob/73368f5909fe4cd7067f4eb687bb862c6441b967/libs/seiscomp/processing/waveformprocessor.h#L42). Sort of a [`Processing::TimeWindowProcessor`](https://github.com/SeisComP/common/blob/73368f5909fe4cd7067f4eb687bb862c6441b967/libs/seiscomp/processing/timewindowprocessor.h#L35) implementing your specific requirements.

**Comment by luca-s** [comment]
> Yes, exactly my point. We could add a complicated implementation which tracks all the time windows and does all the complicated setup stuff and then only one application we do not even know uses it. ;)

This is a valid point, I don't have anything else to say. 

>So when you subscribe to the data of all your events per day, then combining all time windows per channel (P and S) is a valid approach. Then feed every record into the processor and let it filter it. The file must be accessed just once. Why isn't that a valid and simple approach?

If there were multiple modules that require that, it would be ugly to implement this workaround in every one of them. Also, the module should implement different strategies depending on the specific RecordStream (SDS vs File vs FDSN....and what about combined or balanced? What about future RecordStream types? The module code cannot and should not be aware of the internal  details of the RecordStream, it should rely on the API). The best place to implement the logic is within each RecordStream implementation. However, because this feature is normally not required, I agree it is an overkill to have it in the API.

So, thanks for the useful discussion, it is always fruitful to discuss SeisComP internal details with you.

**Comment by luca-s** [comment]
@damb Thanks, I will have a look at it. However I don't have issues in implementing a workaround, I have done it already. I just would like to move the workaround at the API level, so that no other modules would have to do it again.

**Comment by luca-s** [comment]
Just to restate my feeling about the current inconsistency across RecordStream implementations: not only some (e.g. fdsn) of them allow to request multiple time windows per stream (net.sta.loc.cha) and some (e.g. sds, seedlink) do not; some (e.g. seedlink) of them don't even allow to request multiple location or channel codes for the same station (see [here](https://github.com/SeisComP/seedlink/issues/7)). Then we can discuss the File implementation that is the weakest of them all (e.g. you cannot reliably use it like `-I file://myfile.mseed` with all the GUIs and expect it to work properly all the time).

This is really an inconsistent implementation of an interface, that behaves differently depending on the specific implementation and constantly breaks expectations.

**Comment by gempa-jabe** [comment]
What means weakest? Doesn't it give you the data you are expecting or more than you were requesting? Actually we can fix all recordstream implementations to support multiple time windows per channels but that is not really required by our modules and many implementations must then emulate this feature as it is not supported by e.g. seedlink, file, memory, sdsarchive. That is why we added the processing application which allows to handle more data as being requested and feed only what is required and requested.

As first step we should merge the requested time windows per channel so that a user always gets at least the requested data and not less. With e.g. seedlink it must be handled at station level.

**Comment by luca-s** [comment]
> What means weakest? Doesn't it give you the data you are expecting or more than you were requesting? 

You can see unexpected behaviours in the GUIs or modules if you use `file` RecordSteam instead of `sdsarchive`.

>  but that is not really required by our modules and many implementations must then emulate this feature as it is not supported

You are right here, I cannot find a good counterargument. However the RecordStream is such a nice abstraction that I expected it to work seamlessly with any implementation and I was disappointed to see that is not fully implemented. 

I have a solution that works with any RecordStream. If one day I find the time I will try to push a PR and see what you think about it.
