### ISSUE TITLE
Buffered record might be fed twice

### ISSUE THREAD

**Issue by damb** [SeisComP/common#48]
Hi,

I stumpled over the issue that a buffered record might be fed twice when registering an instance of `processing::TimeWindowProcessor` in https://github.com/SeisComP/common/blob/fc5d683f14883702498de59903435150b6f31bcd/libs/seiscomp/processing/application.cpp#L195

Particularly, it is the last buffered record which is the one fed twice iff the instance of `processing::TimeWindowProcessor` did not finish during registration, already. The record is fed a second time here https://github.com/SeisComP/common/blob/fc5d683f14883702498de59903435150b6f31bcd/libs/seiscomp/processing/application.cpp#L470

Have you been aware of this issue? Is this by design?

I'm aware the record's fed twice are usually dropped with https://github.com/SeisComP/common/blob/fc5d683f14883702498de59903435150b6f31bcd/libs/seiscomp/processing/waveformprocessor.cpp#L285

What do you think about performing the check client-side for `processing::TimeWindowProcessor`s? I.e. by means of e.g. adding

```cpp
if ( it->second->lastRecord() == rec ) continue;
```

before https://github.com/SeisComP/common/blob/fc5d683f14883702498de59903435150b6f31bcd/libs/seiscomp/processing/application.cpp#L470-L472

**Comment by gempa-jabe** [comment]
Thank you for digging into it although I can't really follow your comment. Is it currently an issue or just another way of avoiding duplicate records?

**Comment by damb** [comment]
Well, given a module such as e.g. `scautopick` which registers `Processing::AmplitudeProcessor`s (i.e. `Processing::TimeWindowProcessors`) once there is a *detection*. During amplitude processor registration records are fed from the waveform buffer. This may include also the last, most recent record buffered (depending on the implementation and required time window of the particular `Processing::AmplitudeProcessor`). Now, if the amplitude processor did not finish (i.e. there is still additional data required) the most recent record is fed twice. Actually, this is no issue, usually records fed twice are simply dropped within `Processing::WaveformProcessor::store()`.

> Is this by design?

The more I think about it, the more I think it is a good design choice. However, if a concrete implementation of `Processing::AmplitudeProcessor` is instantiated with a `Processing::WaveformOperator` the concrete implementation of the operator must handle duplicate records, too. In this case, my proposal from above (i.e. checking whether the last record of the amplitude processor is the same as the current record) wouldn't solve the issue.

To conclude, with the current API it is difficult to avoid feeding duplicate records. If a client of the API really want's to avoid feeding duplicate records it needs to keep track of the last records fed by itself.

From my point of view, therefore, we can close this issue.

**Comment by gempa-jabe** [comment]
I see. So the point is to avoid feeding duplicate records in `Application::handleRecord`.  There is code between `_waveformBuffer.feed` and `it->second->feed` and that is the only place which could add a new `TimeWindowProcessor` and feed already available data which would include the current record. Registration must then be triggered by `handleNewStream` from what I can see. The easiest option would be to first feed existing procs and then add data to the buffer and emit `handleNewStream`. What do you think?

**Comment by damb** [comment]
I agree :+1:.

**Comment by gempa-jabe** [comment]
I have pushed a fix with 6b650443cfc9659010ac62e18c9cd491bf959376. I hope that it won't break anything. Are you able to give it a try and check the issue you have experienced?

**Comment by damb** [comment]
> Are you able to give it a try and check the issue you have experienced?

Unfortunately, no. I was reading the code, spotted the issue and wrote this issue in order to let you know. Currently, I'm not using `Processing::Application` in my code, (yet).

**Comment by damb** [comment]
BTW, there seems to be some unused variable: https://github.com/SeisComP/common/blob/9f30d6a6fcab3307cd868891370eb8e64a6c21dd/libs/seiscomp/processing/application.cpp#L447

**Comment by gempa-jabe** [comment]
Actually it is not unused. It is a smart pointer which destroys the incoming record if it hasn't been used somewhere else. The caller transfers ownership to the `handleRecord` method which in turn makes sure that there is no memory leak.

**Comment by gempa-jabe** [comment]
> Unfortunately, no. I was reading the code, spotted the issue and wrote this issue in order to let you know.

OK. So I took the opportunity to check and hopefully fix it.

**Comment by damb** [comment]
>   OK. So I took the opportunity to check and hopefully fix it.

Thanks.

**Comment by damb** [comment]
> The caller transfers ownership to the `handleRecord` method which in turn makes sure that there is no memory leak.

Oh. Isn't the ownership managed by the caller? I mean, a raw pointer is passed. Also, https://github.com/SeisComP/common/blob/9f30d6a6fcab3307cd868891370eb8e64a6c21dd/libs/seiscomp/client/streamapplication.h#L114 doesn't mention that the ownership of `rec` is transferred.

**Comment by gempa-jabe** [comment]
Yep, a raw pointer is passed and the caller does neither store it in a smart pointer nor does it delete it at some point later. It was allocated most likely in the recordstream thread and passed to the application for further handling. So the `handleRecord` implementation is responsible to destroy the object. Ownership management is sometimes difficult and the decision was at the time of writing that code that `handleRecord` receives a raw pointer (rather than a smart pointer) that it must manage itself. The semantics of a raw pointer is sometimes not obvious and the documentation is the only place that would help. A note will be added. Thanks.

**Comment by damb** [comment]
> A note will be added.

Perfect. Thanks for the clarification, @gempa-jabe.

I think, we can close this issue.
