### ISSUE TITLE
Compilation error with recent commits (16-17 August 2020)

### ISSUE THREAD

**Issue by a-oth** [SeisComP/common#5]
Hello, 
When compiling on macOS including the recent commits (16-17 August 2020), I get the following compilation error. Could this be related to the recent changes? Compiling prior to integrating these changes with commits up to 14 August 2020 included works just fine.

Many thanks for giving a look!

Undefined symbols for architecture x86_64:
  "Seiscomp::Math::Filtering::IIR::ButterworthBandpass<double>::ButterworthBandpass(int, double, double, double)", referenced from:
      Seiscomp::Processing::BKPicker::calculatePick(int, double const*, int, int, int&, int&, int&, double&, boost::optional<Seiscomp::Processing::Picker::Polarity>&) in bk.cpp.o
      Seiscomp::Processing::GFZPicker::calculatePick(int, double const*, int, int, int&, int&, int&, double&, boost::optional<Seiscomp::Processing::Picker::Polarity>&) in gfz.cpp.o
  "Seiscomp::Math::Filtering::IIR::ButterworthHighpass<double>::ButterworthHighpass(int, double, double)", referenced from:
      Seiscomp::Processing::AmplitudeProcessor_Mwp::computeAmplitude(Seiscomp::NumericArray<double> const&, unsigned long, unsigned long, unsigned long, unsigned long, double, Seiscomp::Processing::AmplitudeProcessor::AmplitudeIndex*, Seiscomp::Processing::AmplitudeProcessor::AmplitudeValue*, double*, double*) in Mwp.cpp.o
      Seiscomp::Processing::QcProcessorSpike::_setFilter(double) in qcprocessor_spike.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libseiscomp_client.14.1.0.dylib] Error 1
make[1]: *** [src/base/common/libs/seiscomp/CMakeFiles/seiscomp_client.dir/all] Error 2

**Comment by andres-h** [comment]
Sounds like dependencies might have been not properly detected and some libraries are out-of-date. Maybe "make clean" would help. Or remove the "build" directory. Eg., recompile everything from scratch.

**Comment by gempa-jabe** [comment]
Check the latest version. I fixed an issue with clang linking. It should work with macOS as well.

**Comment by a-oth** [comment]
Thanks for your answers, the clang fix solved the problem and the code compiles fine again.

As a side note, I have to use boost version 1.72 though, with the current version 1.73 in homebrew, I get additional compilation issues:
```
In file included from .../seiscomp4-git/seiscomp4-macos-master-2020-08-17-v4.1.0d/src/base/common/libs/seiscomp/gui/map/layers/geofeaturelayer.cpp:20:
In file included from .../seiscomp4-git/seiscomp4-macos-master-2020-08-17-v4.1.0d/src/base/common/libs/seiscomp/gui/core/application.h:29:
In file included from .../seiscomp4-git/seiscomp4-macos-master-2020-08-17-v4.1.0d/src/base/common/libs/seiscomp/client/application.h:40:
In file included from .../seiscomp4-git/seiscomp4-macos-master-2020-08-17-v4.1.0d/src/base/common/libs/seiscomp/messaging/connection.h:27:
In file included from .../seiscomp4-git/seiscomp4-macos-master-2020-08-17-v4.1.0d/src/base/common/libs/seiscomp/utils/timer.h:30:
In file included from /usr/local/opt/boost/include/boost/thread/thread.hpp:12:
In file included from /usr/local/opt/boost/include/boost/thread/thread_only.hpp:22:
In file included from /usr/local/opt/boost/include/boost/thread/detail/thread.hpp:33:
/usr/local/opt/boost/include/boost/bind/bind.hpp:592:16: error: no matching function for call to object of type 'boost::_mfi::mf5<bool, Seiscomp::Gui::Map::GeoFeatureLayer, Seiscomp::Gui::Map::Canvas *, QPainter *, const
      QPen *, Seiscomp::Gui::Map::GeoFeatureLayer::LayerProperties *, const Seiscomp::Geo::GeoFeature *>'
        return unwrapper<F>::unwrap(f, 0)(a[base_type::a1_], a[base_type::a2_], a[base_type::a3_], a[base_type::a4_], a[base_type::a5_], a[base_type::a6_]);
```

This seems not related to these recent commits, but I thought I'd let you know in any case.
Cheers
Adrien

**Comment by gempa-jabe** [comment]
Thanks for letting me know.
