### ISSUE TITLE
Clarification on `NumericArray<T>::absMax()`

### ISSUE THREAD

**Issue by damb** [SeisComP/common#52]
Hi devs,

a question regarding https://github.com/SeisComP/common/blob/399d98c2d709f24ecf0f4bc27f759cefa76dc2f3/libs/seiscomp/core/typedarray.h#L194-L195

As a client of this API and according to the documentation I'd expect that the returned value is always >= 0. Though, the implementation is different, see: https://github.com/SeisComP/common/blob/399d98c2d709f24ecf0f4bc27f759cefa76dc2f3/libs/seiscomp/core/typedarray.cpp#L425-L428.

I.e. the comparison is performed based on absolute values, however the returned value may still be negative.

Is this on purpose?

**Comment by gempa-jabe** [comment]
Yes, this is on purpose. Calling abs() for a client on the returned value is easy. Figuring out whether the value was negative or positive is impossible if it still wants to get the largest amplitude regardless of polarization. Numpy returns an index which can be used to get the real value. Our implementation returns the real value and the function just names how this value is being searched for.

**Comment by damb** [comment]
Thanks, @gempa-jabe, for clarifying.
