### ISSUE TITLE
libs/xml XSD file typo - type should be "tremor pulse" instead

### ISSUE THREAD

**Issue by salichon** [SeisComP/common#59]
- tremor pulse type enumeration misses the "r"
https://github.com/SeisComP/common/blob/8b0e478ff201eb7c25d84ebe6b32ec3642008089/libs/xml/0.12/sc3ml_0.12.xsd#L160

cheers
jerome

**Comment by gempa-jabe** [comment]
Fixed with 3d943d5e35ba53d6aee4049c6bb5fc4eb07df5f3
