### ISSUE TITLE
[aic picker] scautopick stops processing the stream after a gap is found

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#81]
I am working in playback with some data that contains gaps. `scautopick` worked fine until I enabled "AIC". With "AIC" as `picker` scautopick stops processing the stream after the first gap is found. 

Here is the results of running `scautopick`  on streams 56G1 and 56G2 when "AIC" is NOT used.

![image](https://user-images.githubusercontent.com/15273575/218132947-40db0591-b1e9-4d5c-97a0-be9918df486f.png)

And here with "AIC".

![image](https://user-images.githubusercontent.com/15273575/218133465-29c40d68-7fef-4beb-a7d2-7a6156190a74.png)

I am running `scautipick` with `gapInterpolation` enabled and `maxGapLength` 4.5 sec

**Comment by luca-s** [comment]
I had a look at the code and I now understand this strange behaviour. 

`AIC` picker class is derived from `Siescomp::Processing::Picker` which does [doesn't handle the gaps](https://github.com/SeisComP/common/blob/8a504984450616082a19c196754f378871befc0b/libs/seiscomp/processing/picker.cpp#L104).

The basic `scautopick` detector class is derived from `Siescomp::Processing::SimpleDetector` instead, which inherits the [gap handling behaviour ](https://github.com/SeisComP/common/blob/8a504984450616082a19c196754f378871befc0b/libs/seiscomp/processing/waveformprocessor.cpp#L426 ) from `Siescomp::Processing::WaveformProcessor`.

I can understand that `AIC` doesn't handle the gaps, but completely stopping the processing of a stream seems a tittle too extreme, don't you agree?

**Comment by gempa-jabe** [comment]
Yes, I agree if that is the case. Actually terminate just sets the status of the AIC processor which causes it to be removed from the processing. The detector is not affected. Maybe there is a logical error which prevents the detector from emitting further picks in such a case. We will look into it. Thanks for reporting.

**Comment by gempa-jabe** [comment]
If possible, can you share your example that I can run it with `scautopick`  to reproduce the issue?

**Comment by luca-s** [comment]
Yes sure, let me prepare the data for you.

**Comment by luca-s** [comment]
[data.tar.gz](https://github.com/SeisComP/common/files/10721221/data.tar.gz)

`scautopick.cfg`:
```
leadTime = 1
initTime = 1
gapInterpolation = true
picker = ""   # or "AIC"
amplitudes = ""
thresholds.triggerOn = 2
thresholds.triggerOff = 1.0
thresholds.deadTime = 0.1
thresholds.minAmplOffset = 2
```

`scautopick` bindings:
```
picker.AIC.signalBegin = -0.03
picker.AIC.signalEnd = 0.02
detecFilter = "RMHP(10)>>BW_HP(4,50)>>STALTA(0.02,0.06)"
timeCorr = 0
```

SeisComP v5.3.0

**Comment by gempa-jabe** [comment]
e68488df022ec4e37166eb92cdf67fae4aed56c6 fixes your issue.

**Comment by luca-s** [comment]
Thanks a lot. I tested it and it works indeed!
