### ISSUE TITLE
Parsing of struct in configuration xml crashes scconfig

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#94]
I have found an issue on the master branch that doesn't happen on branch v5. Due to the recent changes on master (`Add support to extend configuration structs with plugins`) I thought this might be related and I am reporting it.

The xml configuration that crashes `scconfig` can be found [here](https://github.com/swiss-seismological-service/seedlink_raw_plugin/blob/main/seedlink/plugins/raw_plugin/descriptions/raw_plugin.xml).

The crash is related to [this line](https://github.com/SeisComP/common/blob/d3bd4b5997dde3a446652da6334ea9ff86742c23/libs/seiscomp/system/model.cpp#L476) and it looks like in my case `it->second` is null. If I add a check on it being null everything works fine, but I don't have the visibility to understand neither the full problem nor the correct bug fix.

Here are the details:

![image](https://github.com/SeisComP/common/assets/15273575/a3868b9c-9b1d-412e-bcd6-5b5817bc6b91)

**Comment by gempa-jabe** [comment]
How can I reproduce it? I copied the description file and added a raw source but no crash happened.

**Comment by luca-s** [comment]
Interesting. It happens all the time on my system. Let me debug it further and I will be back to you.

**Comment by luca-s** [comment]
How to reproduce:
- download SeisComP nightly build
- copy raw_plugin.xml to etc/descriptions/
- run scconfig
- create a seedlink profile
- Add a raw source
- After pressing the + button on the raw source scconfig crashes

**Comment by gempa-jabe** [comment]
Ok, could reproduce it. With an existing source it worked so far. Anyway, I am going to check it.

**Comment by luca-s** [comment]
Thanks!

**Comment by gempa-jabe** [comment]
Fixed with 6ae0a2ea9a54117b1770325fa7761a8d50b8f97b

**Comment by luca-s** [comment]
Perfect, that solves the issue. I fixed that myself like that but I wasn't sure it made sense to have a null pointer in there.

**Comment by gempa-jabe** [comment]
Yes it makes sense if the variable (`sources` in this example) is not yet set.
