### ISSUE TITLE
[scolv/picker] Maximise visible amplitude

### ISSUE THREAD

**Issue by FMassin** [SeisComP/common#96]
Hello

We are using v5.4.0 and none of the button or menu to [**Maximise visible amplitude**](https://github.com/SeisComP/common/blob/b30729ddaebe78c1e6bcb00f269c784e5cbfaba4/libs/seiscomp/gui/datamodel/pickerview.cpp#L2995) or its shortcut (`s`) work to rescale the seismogram in the selected station picker window (it does still work in the mutli-station waveform section subplot).

Is this already fixed in newer versions maybe?

Cheers

Fred
<img width="857" alt="Screenshot 2023-07-12 at 15 15 42" src="https://github.com/SeisComP/common/assets/10435362/5ab860db-e049-4764-82c9-43c6a57e3306">

**Comment by jsaul** [comment]
This also confused me but AFAICS the same amplitude scaling can be achieved using 'w' instead of 's'.

**Comment by gempa-jabe** [comment]
What is your expectation of the operation and has it changes w.r.t. another version?

**Comment by jsaul** [comment]
> overscaling (ctrl+up/down) will not be reset

Not any more, but it was reset via 's' previously.

**Comment by FMassin** [comment]
**s** (or button, or menu) use to reset the amplitude of the seismograms in the picker window selected with the pointer, useful after playing with amplitude exaggeration. 

This feature was working in all `scolv` versions that I (and others in our group) knew of, until we migrated to v5.4. Since then, it works only on the multistation subplots, not on the single station subplot.

On my screenshot, the amplitude of the  single station subplot is exaggerated manually. Before v5.4, I would just press **s** to reset the amplitude scale to see the full dynamic. Since v5.4 I need to readjust manually.

**Comment by gempa-jabe** [comment]
Ok, got it. Note that 's' toggles something, it does not just trigger an action.

**Comment by gempa-jabe** [comment]
"Got it" means that we will look into it and restore the old behaviour.

**Comment by FMassin** [comment]
> Note that 's' toggles something, it does not just trigger an action.
Ok 🧐

Thanks a lot @gempa-jabe !

**Comment by gempa-jabe** [comment]
Forget about the toggle thing in scolv. It is in scrttv the case.

**Comment by gempa-jabe** [comment]
The issue has been fixed in master branch and v5. Will be in 5.5.

**Comment by FMassin** [comment]
Sorry one more question: can I patch with https://github.com/SeisComP/common/commit/ce6130aaf1d4410757382c3da076c12eef286237 without upgrading ?

**Comment by gempa-jabe** [comment]
Yes
